# .streamlit/secrets.toml
# Bu dosyayı Streamlit Cloud'da Settings > Secrets kısmına ekle

SUPABASE_URL = "https://ckxbytrgxrdrxtkbaqex.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreGJ5dHJneHJkcnh0a2JhcWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NzYyNjAsImV4cCI6MjA1MzI1MjI2MH0.BURAYA_ANON_KEY_GELECEK"
